# Exported from Render on 2024-06-05T08:40:58Z
services:
- type: web
  name: MyanmarTender
  runtime: python
  repo: https://github.com/arkerphyo92/mmtender
  plan: free
  envVars:
  - key: DJANGO_SETTINGS_MODULE
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: ALLOWED_HOSTS
    sync: false
  - key: PRODUCTION
    sync: false
  - key: DEBUG
    sync: false
  - key: SECRET_KEY
    sync: false
  region: singapore
  buildCommand: pip install -r requirements/base.txt
  startCommand: gunicorn tender.wsgi:application
version: "1"
