# Generated by Django 5.0.6 on 2024-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingtender_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='type',
            field=models.CharField(choices=[('Opened Tender', 'Open Tender'), ('Closed Tender', 'Closed Tender')], default='Opened Tender', max_length=15),
        ),
    ]
