# Generated by Django 5.0.6 on 2024-05-26 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listingtender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtender',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listingtender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
