# Generated by Django 5.0.6 on 2024-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingtender_created_at_listingtender_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='description',
            field=models.TextField(),
        ),
    ]
