# Generated by Django 5.0.6 on 2024-05-26 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listingtender_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='attpdf',
            field=models.FileField(upload_to='tenders/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
