# Generated by Django 5.0.6 on 2024-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listingtender_attpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtender',
            name='attpdf_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
