# Generated by Django 5.0.6 on 2024-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingtender_attpdf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingtender',
            name='attpdf_name',
        ),
        migrations.AddField(
            model_name='listingtender',
            name='att_name',
            field=models.CharField(default='File Name', max_length=255),
        ),
    ]
