# Generated by Django 5.0.6 on 2024-05-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listingtender_attpdf_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='closedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listingtender',
            name='opendate',
            field=models.DateField(),
        ),
    ]
