# Generated by Django 5.0.6 on 2024-05-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listingtender_closedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='att_name',
            field=models.CharField(max_length=255),
        ),
    ]
