# Generated by Django 5.0.6 on 2024-05-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listingtender_att_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.fields'),
        ),
    ]
