# Generated by Django 5.0.6 on 2024-05-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listingtender_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtender',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tenders/images/'),
        ),
    ]
