# Generated by Django 5.0.6 on 2024-05-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listingtender_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingtender',
            name='att_name',
        ),
    ]
