# Generated by Django 5.0.6 on 2024-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_remove_listingtender_att_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='tenders/images/'),
        ),
    ]
