# Generated by Django 5.0.6 on 2024-05-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listingtender_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingtender',
            old_name='image',
            new_name='attimage',
        ),
    ]
