# Generated by Django 5.0.6 on 2024-05-31 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_rename_image_listingtender_attimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtender',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
